### PR TITLE
Connect to Api

### PR DESCRIPTION
**Pull request by mckent05**
## In this PR, I have done the following:

- Used redux-thunk to connect my app to the Bookstore API
- Refactored my redux code to use middleware for making async calls to the API
- Ensured that my refactored code still works the same
- Ensured that I have met all project requirements

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Tope,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby
- Checks are failing. Kindly ensure that **all** checks are passing.
 - You have submitted a project,  _Eslint_ is not properly configured. This is **required** to ensure that your code is quality and robust. Kindly ensure to improve upon this aspect, by following the installation guide from this [link](https://github.com/microverseinc/linters-config/tree/master/react-redux).

**Eslint error:**
image


 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mckent05** [comment]
Hello @rloterh thanks for the review, 
All checks are passing on my side. Please can you check to confirm the issues arent from your end.

**Comment by rloterh** [comment]
Hi @mckent05 
Kindly ensure that the checks with Netlify are passing as well. Kindly note that **all** checks must pass.

**Failing checks:**
image

Also, kindly reinstall **Eslint** using the recommended approach, as mentioned in the earlier review, without any modification(s) to it.

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @mckent05, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
